### ISSUE TITLE
Unable to build on xcode Version 7.3 after updating to ver. 1.37.3

### ISSUE THREAD

**Issue by gkye** [CosmicMind/Material#255]
After updating my pods and updating Material to 1.37.3 I'm unable to build any projects which include Material. I keep received this same error. (I've clean derived data multiple times and even reinstalled Material)
`error: /Users/george/Library/Developer/Xcode/DerivedData/MaterialTest-hegneggavllamfdegkkiaqicdmzu/Build/Products/Debug-iphonesimulator/Material/io.cosmicmind.Material.bundle: No such file or directory`
I've also noticed another target show up within my Pods project. (screenshot below)
 I've tested this with many new projects i still receive the same error.
Test project available [here](https://github.com/gkye/MaterialTest)

![Error](http://i.imgur.com/lTAfbop.png)

**Comment by danieldahan** [comment]
This is strange. This could be an issue with how CocoaPods handles bundles, and the added MaterialIcon library for icons that are bundled with Material. I'll look into this before I send out a release today. Thanks!

**Comment by danieldahan** [comment]
Hey, I released 1.38.0 now. Made a CocoaPods project and installed using Xcode 7.3. All seemed to work. If you have any further issues, please reopen or create a new issue. All the best!

**Comment by neugartf** [comment]
Ran into the same problem, deleting the target that you selected solved the issue though.

**Comment by danieldahan** [comment]
Try [1.38.5](https://github.com/CosmicMind/Material/releases/tag/1.38.5).

**Comment by elsesiy** [comment]
@danieldahan Doesn't fix the problem for me. Still need to remove the target being created..

**Comment by danieldahan** [comment]
That is weird. I have created an empty project and installed the pods without an issue. I am going to be making another release today or tomorrow, so I will double check all corners to see if I can find anything. Sorry about that.

**Comment by elsesiy** [comment]
No worries, deleting the target works fine :+1: Thanks for the quick reply though!
